// src/routes/root/RootPage.svelte
<script lang="ts">
  import GithubIcon from "../../lib/icons/GithubIcon.svelte";
  import GmailIcon from "../../lib/icons/GmailIcon.svelte";
  import LinkedInIcon from "../../lib/icons/LinkedInIcon.svelte";
  import TelegramIcon from "../../lib/icons/TelegramIcon.svelte";

  import DecimalAge from "../../lib/DecimalAge.svelte";
  import SocialIcon from "../../lib/SocialIcon.svelte";
  import StyledLink from "../../lib/StyledLink.svelte";
  import Badge from "../../lib/Badge.svelte";
  import JourneyCard from "../../lib/JourneyCard.svelte";
  import { getKyivTimeZoneInfo } from "../../lib/utils";

  import { aboutMe, myEmail, myUrls, skillsStack, skillsStackAdditional } from "../../data/about";
    import RootContainer from "../../lib/RootContainer.svelte";

    const timeInfo = getKyivTimeZoneInfo();
</script>

        <div class="flex flex-col gap-6 mt-2 text-foreground/90">
            <section class="flex flex-col gap-3">
                <div class="flex items-center justify-between">
                    <h1 class="text-3xl font-bold tracking-tight">
                        Viktor Varenik
                    </h1>
                    <div class="flex gap-3">
                        <SocialIcon
                            iconComponent={GmailIcon}
                            destinationUrl={'mailto:' + myEmail}
                            label="Gmail"
                        />
                        <SocialIcon
                            iconComponent={LinkedInIcon}
                            destinationUrl={myUrls.linkedin}
                            label="Linkedin"
                        />
                        <SocialIcon
                            iconComponent={TelegramIcon}
                            destinationUrl={myUrls.telegram}
                            label="Telegram"
                        />
                        <SocialIcon
                            iconComponent={GithubIcon}
                            destinationUrl={myUrls.github}
                            label="Github"
                        />
                    </div>
                </div>
                <p class="text-muted-foreground leading-relaxed">
                    {aboutMe}
                </p>
            </section>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <section class="flex flex-col">
                    <p class="font-semibold">verbose.</p>
                    <div class="flex flex-col gap-2 text-sm mt-2">
                        <div class="flex justify-between items-center border-b border-border/50 pb-1">
                            <span class="font-bold">Position</span>
                            <span class="text-muted-foreground text-right">
                                Full-stack Engineer
                            </span>
                        </div>
                        <div class="flex justify-between items-center border-b border-border/50 pb-1">
                            <span class="font-bold">Location</span>
                            <a
                                href="https://www.google.com/maps/place/Kharkiv"
                                target="_blank"
                                class="text-muted-foreground hover:underline underline-offset-4 decoration-dotted text-right"
                            >
                                Ukraine, Kharkiv
                            </a>
                        </div>
                        <div class="flex justify-between items-center border-b border-border/50 pb-1">
                            <span class="font-bold">Timezone</span>
                            <span
                                class="text-muted-foreground text-right"
                                title={timeInfo.season}
                            >
                                {timeInfo.utcOffset}
                            </span>
                        </div>
                        <div class="flex justify-between items-center border-b border-border/50 pb-1">
                            <span class="font-bold">Age</span>
                            <span class="text-muted-foreground text-right">
                                <DecimalAge birthDate="2002-09-02T03:24:00" />{' '}
                                years
                            </span>
                        </div>
                        <div class="flex justify-between items-center border-b border-border/50 pb-1">
                            <span class="font-bold">Education</span>
                            <span class="text-muted-foreground text-right">
                                Non-technical
                            </span>
                        </div>
                    </div>
                </section>

                <section class="flex flex-col">
                    <p class="font-semibold">languages.</p>
                    <div class="flex flex-col gap-2 text-sm mt-2">
                        <div class="flex justify-between border-b border-border/50 pb-1">
                            <span class="font-bold">Ukrainian</span>
                            <span class="text-muted-foreground">
                                Native
                            </span>
                        </div>
                        <div class="flex justify-between border-b border-border/50 pb-1">
                            <span class="font-bold">Russian</span>
                            <span class="text-muted-foreground">
                                Native
                            </span>
                        </div>
                        <div class="flex justify-between border-b border-border/50 pb-1">
                            <span class="font-bold">English</span>
                            <span class="text-muted-foreground">
                                Upper-Intermediate (B2)
                            </span>
                        </div>
                    </div>
                </section>
            </div>

            <section class="mt-4">
                <p class="font-semibold">skills.</p>

                <div class="mt-2 flex flex-row flex-wrap gap-2">
                    {#each skillsStack as skill}
                      <Badge label={skill} />
                    {/each}
                </div>

                <p class="mt-2 mb-1 text-sm">Additional stack:</p>
                <div class="flex flex-row flex-wrap gap-2">
                    {#each skillsStackAdditional as skill}
                      <Badge label={skill} />
                    {/each}
                </div>
            </section>

            <section class="mt-4">
                <p class="font-semibold">journey.</p>
                <div class="mt-2">
                    <JourneyCard
                        title="Android&iOS Developer"
                        companyTitle="AppLead Pro & VIPAPP & Gravity"
                        companyUrl={undefined}
                        workingDates="jan 2019 - dec 2024"
                        description="For more than four years, I was deeply immersed in native mobile development. This foundational chapter of my career was spent building, launching, and maintaining robust applications for both Android (Kotlin) and iOS (Swift)."
                    />
                    <JourneyCard
                        title="Full-stack Developer"
                        companyTitle="Freelance"
                        companyUrl={undefined}
                        workingDates="nov 2024 - now"
                        description="As a freelance developer, I take full ownership of building modern web applications. I use a powerful stack including React, Node.js, and TypeScript to deliver production-ready code for my clients."
                    />
                </div>
            </section>

            <section class="flex flex-col" hidden={true}>
                <p class="font-semibold">devices.</p>
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm mt-2">
                    <div class="p-3 border rounded-lg bg-card/30">
                        <h3 class="font-semibold text-muted-foreground mb-2 text-xs uppercase tracking-wider">
                            Workstations
                        </h3>
                        <ul class="list-disc list-inside space-y-1">
                            <li>PC: AMD Ryzen 7 5700X</li>
                            <li>MacBook Air M1 8/256</li>
                        </ul>
                    </div>
                    <div class="p-3 border rounded-lg bg-card/30">
                        <h3 class="font-semibold text-muted-foreground mb-2 text-xs uppercase tracking-wider">
                            Home Lab
                        </h3>
                        <ul class="list-disc list-inside space-y-1">
                            <li>HP Elitedesk G4 DM</li>
                        </ul>
                    </div>
                    <div class="p-3 border rounded-lg bg-card/30">
                        <h3 class="font-semibold text-muted-foreground mb-2 text-xs uppercase tracking-wider">
                            Mobile
                        </h3>
                        <ul class="list-disc list-inside space-y-1">
                            <li>iPhone 12 256Gb (Main)</li>
                            <li class="text-muted-foreground">
                                OnePlus Nord N10
                            </li>
                            <li class="text-muted-foreground">
                                Xiaomi Redmi Note 9
                            </li>
                            <li class="text-muted-foreground">
                                Xiaomi Redmi S2
                            </li>
                        </ul>
                    </div>
                    <div class="p-3 border rounded-lg bg-card/30">
                        <h3 class="font-semibold text-muted-foreground mb-2 text-xs uppercase tracking-wider">
                            Entertainment
                        </h3>
                        <ul class="list-disc list-inside space-y-1">
                            <li class="flex items-center gap-2">
                                Nintendo Switch rev 2
                            </li>
                            <li class="flex items-center gap-2">
                                Oculus Quest 2
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <section class="mt-4">
                <p class="font-semibold">contact.</p>
                <p>
                    interested in a conversation? drop dm's over{' '}
                    <StyledLink href={myUrls.linkedin}>Linkedin</StyledLink>,{' '}
                    <StyledLink href={myUrls.telegram}>Telegram</StyledLink> or{' '}
                    <StyledLink href={'mailto:' + myEmail}>
                        {myEmail}
                    </StyledLink>
                    . ask me anything about my work, projects, or anything else.
                </p>
            </section>

            <section class="mt-4">
                <div class="flex flex-row gap-2 text-muted-foreground">
                    <p>version {(globalThis as any).APP_VERSION}</p>
                    <!-- | -->
                    <!-- <StyledLink href="/status">status</StyledLink> -->
                </div>
            </section>
        </div>

// src/routes/RootPage.tsx
import type {ReactNode} from 'react';
import {DecimalAge} from '@/components/decimal-age';
import {JourneyCard} from '@/components/journey-card';
import {Panel} from '@/components/panel';
import {getKyivTimeZoneInfo} from '@/lib/utils';

type DetailResolver = () => ReactNode;

interface Detail {
    title: string;
    resolver: DetailResolver;
}

interface Social {
    name: string;
    url: string;
}

interface Language {
    name: string;
    levelName: string;
}

interface Bio {
    fullName: string;
    description: string;
    details: Detail[];
    additional: string[];
    socials: Social[];
    email: string;
    languages: Language[];
}

class BioBuilder {
    private data: Bio = {
        fullName: '',
        description: '',
        details: [],
        additional: [],
        socials: [],
        email: '',
        languages: [],
    };

    base(fullName: string, description: string): this {
        this.data.fullName = fullName;
        this.data.description = description;
        return this;
    }

    detail(title: string, resolver: DetailResolver): this {
        this.data.details.push({title, resolver});
        return this;
    }

    contact(name: string, url: string): this {
        this.data.socials.push({name, url});
        return this;
    }

    mail(email: string): this {
        this.data.email = email;
        return this;
    }

    language(name: string, levelName: string): this {
        this.data.languages.push({name, levelName});
        return this;
    }

    build(): Bio {
        return this.data;
    }
}

const bio = new BioBuilder()
    .base(
        'Viktor Varenik',
        `I'm a software engineer focused on software efficiency, simplicity and freedom. I also enjoy recreational programming, reverse engineering and networking. Previously, I developed native mobile applications for Android and iOS.`,
    )
    .detail(
        'Position',
        () => 'Full Stack Software Engineer | Infrastructure & DevOps',
    )
    .detail('Location', () => 'Kremenchuk, Ukraine')
    .detail('Timezone', () => getKyivTimeZoneInfo().utcOffset ?? '?')
    .detail('Age', () => <DecimalAge birthDate="2002-09-02" />)
    // .detail('Education', () => "Bachelor's Diploma \n(Machinery engineering)")
    .detail('Devices', () => 'PC with AMD Ryzen 7 5700X, MacBook Air M1')
    .detail(
        'Smartphones',
        () => 'iPhone 12, OnePlus Nord N10, Xiaomi S2 and Xiaomi Redmi Note 9',
    )
    .detail('OS', () => 'Arch Linux on PC and Laptop')
    .language('English', 'Upper-Intermediate (B2)')
    .language('Ukrainian', 'Native')
    .language('Russian', 'Native')
    .mail('yavarenikya@gmail.com')
    .contact('Github', 'https://github.com/kotleni')
    .contact('Linkedin', 'https://www.linkedin.com/in/kotleni/')
    .contact('Telegram', 'https://t.me/kotleni')
    .contact('X', 'https://x.com/kotleni_')
    .build();

const links = [
    ...bio.socials.map(social => ({
        name: social.name.toLowerCase(),
        url: social.url,
        display: social.url.replace(/^https?:\/\//, '').replace(/\/$/, ''),
    })),
    {
        name: 'email',
        url: `mailto:${bio.email}`,
        display: bio.email,
    },
];

export function RootPage() {
    return (
        <div className="flex flex-col gap-6">
            <header className="flex flex-col gap-3">
                <div className="flex flex-wrap items-center gap-x-2 text-[0.7rem] uppercase tracking-[0.18em] text-muted-foreground">
                    <span className="text-accent">software engineer</span>
                    <span aria-hidden="true">///</span>
                    <span>@kotleni</span>
                </div>
                <h1 className="text-3xl font-bold leading-tight text-foreground sm:text-4xl">
                    {bio.fullName}
                </h1>
                <p className="max-w-prose text-muted-foreground">
                    {bio.description}
                </p>
            </header>

            <Panel title="verbose.txt">
                <dl className="flex flex-col gap-2">
                    {bio.details.map(detail => (
                        <div
                            key={detail.title}
                            className="flex flex-col gap-0.5 sm:flex-row sm:items-baseline sm:gap-2"
                        >
                            <dt className="shrink-0 text-[0.7rem] uppercase tracking-[0.14em] text-muted-foreground sm:w-32">
                                {detail.title}
                            </dt>
                            <dd className="flex min-w-0 flex-1 items-baseline gap-2">
                                <span className="whitespace-pre-wrap">
                                    {detail.resolver()}
                                </span>
                                <span className="leader" aria-hidden="true" />
                            </dd>
                        </div>
                    ))}
                </dl>
            </Panel>

            <Panel title="languages.txt">
                <div className="flex flex-wrap gap-2">
                    {bio.languages.map(language => (
                        <span
                            key={language.name}
                            className="win px-2 py-1 text-sm"
                        >
                            <span className="font-bold text-foreground">
                                {language.name}
                            </span>
                            <span className="text-muted-foreground">
                                {' :: '}
                                {language.levelName}
                            </span>
                        </span>
                    ))}
                </div>
            </Panel>

            <Panel title="journey.log">
                <div className="flex flex-col divide-y divide-dashed divide-border">
                    <JourneyCard
                        title="Android&iOS Developer"
                        companyTitle="AppLead Pro & VIPAPP & Gravity"
                        companyUrl={undefined}
                        workingDates="jan 2019 - dec 2024"
                        description="For more than four years, I was deeply immersed in native mobile development. This foundational chapter of my career was spent building, launching, and maintaining robust applications for both Android (Kotlin) and iOS (Swift)."
                    />
                    <JourneyCard
                        title="Full-stack Developer"
                        companyTitle="Freelance"
                        companyUrl={undefined}
                        workingDates="nov 2024 - now"
                        description="As a freelance developer, I take full ownership of building modern web applications. I use a powerful stack including React, Node.js, and TypeScript to deliver production-ready code for my clients."
                    />
                    <JourneyCard
                        title="React Developer"
                        companyTitle="Intetics Team"
                        companyUrl="https://intetics.com/"
                        workingDates="nov 2024 - now"
                        description="Developing responsive web applications for various clients using React and Next.js. Focused mostly on front-end (mobile-first), integration with APIs, state management, and performance optimization."
                    />
                </div>
            </Panel>

            <Panel title="links.html">
                <p className="text-muted-foreground">
                    interested in a conversation? ask me anything about my work
                    and projects.
                </p>
                <dl className="mt-3 flex flex-col gap-1.5">
                    {links.map(link => (
                        <div
                            key={link.name}
                            className="flex items-baseline gap-2"
                        >
                            <dt className="shrink-0 text-[0.7rem] uppercase tracking-[0.14em] text-muted-foreground">
                                {link.name}
                            </dt>
                            <span className="leader" aria-hidden="true" />
                            <dd className="min-w-0 truncate">
                                <a
                                    href={link.url}
                                    className="text-accent underline decoration-dotted underline-offset-2 hover:decoration-solid"
                                >
                                    {link.display}
                                </a>
                            </dd>
                        </div>
                    ))}
                </dl>
            </Panel>
        </div>
    );
}
