// src/lib/DecimalAge.svelte
<script lang="ts">
    import {onDestroy} from 'svelte';

    interface Props {
        birthDate: string;
    }

    const {birthDate}: Props = $props();

    const ONE_YEAR_IN_MS = 31556952000;
    let preciseAge: string = $state('0');

    const update = () => {
        const now = new Date().getTime();
        const birth = new Date(birthDate).getTime();
        const diff = now - birth;

        const exactAge = diff / ONE_YEAR_IN_MS;
        preciseAge = exactAge.toFixed(9);
    };

    const updateInterval = setInterval(update, 50);

    onDestroy(() => {
        clearInterval(updateInterval);
    });
</script>

<p class="monospace">{preciseAge}</p>

// src/components/decimal-age.tsx
import {useEffect, useState} from 'react';
import {Tooltip, TooltipContent, TooltipTrigger} from '@/components/ui/tooltip';

interface DecimalAgeProps {
    birthDate: string;
}

export const DecimalAge = ({birthDate}: DecimalAgeProps) => {
    const [age, setAge] = useState<string | null>(null);

    useEffect(() => {
        const ONE_YEAR_IN_MS = 31556952000;

        const calculateAge = () => {
            const now = new Date().getTime();
            const birth = new Date(birthDate).getTime();
            const diff = now - birth;

            const exactAge = diff / ONE_YEAR_IN_MS;
            setAge(exactAge.toFixed(9));
        };

        calculateAge();

        const intervalId = setInterval(calculateAge, 1000);

        return () => clearInterval(intervalId);
    }, [birthDate]);

    if (!age) return null;

    return (
        <Tooltip>
            <TooltipTrigger className="font-mono">{age}</TooltipTrigger>
            <TooltipContent>
                <p>Detailed age as decimal number.</p>
            </TooltipContent>
        </Tooltip>
    );
};
