// src/lib/StyledLink.svelte
<script lang="ts">
    import type { HTMLAnchorAttributes } from 'svelte/elements';
    interface Props extends HTMLAnchorAttributes { };
    const { children, ...otherProps }: Props = $props();
</script>

<a
  {...otherProps}
  class="text-primary hover:bg-primary hover:text-background"
>
  {@render children?.()}
</a>

// src/components/styled-link.tsx
import {cn} from '@/lib/utils';
import {HTMLProps} from 'react';

type StyledLinkProps = HTMLProps<HTMLAnchorElement>;

export function StyledLink(props: StyledLinkProps) {
    return (
        <a
            {...props}
            className={cn(
                props.className,
                'text-primary hover:bg-primary hover:text-background',
            )}
        />
    );
}
