// src/App.tsx
import {useEffect} from 'react';
import clsx from 'clsx';
import {House, NotebookText} from 'lucide-react';
import {Navigate, NavLink, Route, Routes, useLocation} from 'react-router-dom';
import RainOverlay from '@/components/RainOverlay';
import BlogPage from '@/routes/BlogPage';
import ReadPage from '@/routes/ReadPage';
import RootPage from '@/routes/RootPage';

const navigationItems = [
    {
        to: '/',
        label: 'Home',
        description: 'About and links',
        icon: House,
    },
    {
        to: '/blog',
        label: 'Blog',
        description: 'Posts and notes',
        icon: NotebookText,
    },
];

function usePreferredDarkMode() {
    useEffect(() => {
        const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');

        const syncTheme = (isDark: boolean) => {
            document.documentElement.classList.toggle('dark', isDark);
        };

        syncTheme(mediaQuery.matches);

        const handleChange = (event: MediaQueryListEvent) => {
            syncTheme(event.matches);
        };

        mediaQuery.addEventListener('change', handleChange);

        return () => {
            mediaQuery.removeEventListener('change', handleChange);
        };
    }, []);
}

export default function App() {
    usePreferredDarkMode();

    const location = useLocation();

    return (
        <main className="flex w-full justify-center px-3 pt-3.5 pb-14 md:px-[18px] md:pt-[26px]">
            <div className="flex w-full max-w-[1160px] flex-col gap-[22px]">
                <header className="relative grid gap-6 border border-line bg-panel px-[18px] py-6 shadow-panel before:absolute before:inset-x-0 before:top-0 before:h-1 before:bg-brand md:px-7 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
                    <div className="flex min-w-0 flex-col gap-2.5">
                        <NavLink
                            className="flex items-center gap-3.5 text-inherit no-underline hover:text-inherit"
                            to="/"
                        >
                            <span className="inline-flex h-12 w-12 shrink-0 items-center justify-center border border-black/20 bg-brand font-mono text-xl font-bold text-white dark:border-white/15">
                                K
                            </span>
                            <span className="flex min-w-0 flex-col gap-1">
                                <span className="font-mono text-[1.08rem] leading-none font-bold tracking-[0.03em]">
                                    kotleni&apos;s web
                                </span>
                                <span className="text-[0.84rem] text-muted-ink max-[560px]:hidden">
                                    personal corner on the internet
                                </span>
                            </span>
                        </NavLink>
                        <p className="m-0 max-w-[38rem] text-[0.92rem] text-muted-ink max-[560px]:hidden">
                            software, linux, infrastructure, and internet notes
                        </p>
                    </div>
                    <nav
                        className="flex flex-wrap justify-start gap-3 lg:justify-end max-[560px]:gap-2"
                        aria-label="Primary navigation"
                    >
                        {navigationItems.map(item => {
                            const Icon = item.icon;

                            return (
                                <NavLink
                                    key={item.to}
                                    to={item.to}
                                    end={item.to === '/'}
                                    className={({isActive}) =>
                                        clsx(
                                            'inline-flex min-w-0 items-center gap-2.5 border border-line bg-panel-strong px-3.5 py-3 text-muted-ink no-underline transition hover:-translate-y-px hover:border-line-strong hover:text-ink max-[560px]:w-full max-[560px]:justify-start',
                                            isActive &&
                                                'border-ink bg-ink text-panel-strong',
                                        )
                                    }
                                >
                                    <Icon className="h-[18px] w-[18px] shrink-0" />
                                    <span className="flex flex-col gap-0.5">
                                        <span className="font-mono text-[0.92rem] leading-none">
                                            {item.label}
                                        </span>
                                        <span className="text-[0.74rem] leading-[1.1] opacity-80 max-[560px]:hidden">
                                            {item.description}
                                        </span>
                                    </span>
                                </NavLink>
                            );
                        })}
                    </nav>
                </header>
                <div
                    key={location.pathname}
                    className="w-full animate-[fade-in_.32s_ease]"
                >
                    <Routes>
                        <Route path="/" element={<RootPage />} />
                        <Route path="/blog" element={<BlogPage />} />
                        <Route path="/blog/:postId" element={<ReadPage />} />
                        <Route path="*" element={<Navigate to="/" replace />} />
                    </Routes>
                </div>
            </div>
            <RainOverlay />
        </main>
    );
}

// src/App.vue
<script setup lang="ts">
import {House, NotebookText} from 'lucide-vue-next';
import {useDark, usePreferredDark} from '@vueuse/core';
import RainOverlay from './components/RainOverlay.vue';

usePreferredDark();
useDark({
    selector: 'html',
    attribute: 'class',
    valueDark: 'dark',
    valueLight: '',
});

const navigationItems = [
    {
        to: '/',
        label: 'Home',
        description: 'About and links',
        icon: House,
    },
    {
        to: '/blog',
        label: 'Blog',
        description: 'Posts and notes',
        icon: NotebookText,
    },
];
</script>

<template>
    <main class="main">
        <header class="topbar">
            <RouterLink class="brand" to="/">
                <span class="brand-mark">
                    <img class="page-icon" width="18" src="/favicon.svg" />
                </span>
                <span class="brand-copy">
                    <span class="page-title">kotleni's web</span>
                    <span class="page-subtitle"
                        >personal corner on the internet</span
                    >
                </span>
            </RouterLink>
            <nav class="navbar" aria-label="Primary navigation">
                <RouterLink
                    v-for="item in navigationItems"
                    :key="item.to"
                    v-slot="{href, navigate, isActive, isExactActive}"
                    :to="item.to"
                    custom
                >
                    <a
                        :href="href"
                        class="nav-link"
                        :class="{
                            'nav-link-active':
                                item.to === '/' ? isExactActive : isActive,
                        }"
                        :aria-current="
                            (item.to === '/' ? isExactActive : isActive)
                                ? 'page'
                                : undefined
                        "
                        @click="navigate"
                    >
                        <component :is="item.icon" class="nav-icon" />
                        <span class="nav-copy">
                            <span class="nav-label">{{ item.label }}</span>
                            <span class="nav-description">{{
                                item.description
                            }}</span>
                        </span>
                    </a>
                </RouterLink>
            </nav>
        </header>
        <RouterView v-slot="{Component}">
            <Transition name="fade" mode="out-in">
                <component :is="Component" />
            </Transition>
        </RouterView>
        <RainOverlay />
    </main>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
    transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
    opacity: 0;
}

.main {
    width: min(100%, 880px);
    padding: 12px 0 32px;
    display: flex;
    flex-direction: column;
    align-items: center;
}

.topbar {
    width: 100%;
    padding: 12px;
    margin-bottom: 18px;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    gap: 16px;

    background-color: var(--color-card);
    border: 1px solid var(--color-border);
    border-radius: 6px;
}

.navbar {
    display: flex;
    justify-content: flex-end;
    gap: 8px;
    flex-wrap: wrap;
}

.brand {
    min-width: 0;
    display: flex;
    align-items: center;
    gap: 12px;
    color: inherit;
    text-decoration: none;
}

.brand:hover {
    color: inherit;
    background: transparent;
}

.brand-mark {
    width: 42px;
    height: 42px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    border-radius: 6px;
    background-color: var(--color-secondary);
    border: 1px solid var(--color-border);
}

.page-icon {
    display: block;
}

.brand-copy {
    min-width: 0;
    display: flex;
    flex-direction: column;
    gap: 3px;
}

.page-title {
    font-size: 1rem;
    font-weight: 700;
    line-height: 1;
    letter-spacing: 0.01em;
}

.page-subtitle {
    color: var(--color-muted-foreground);
    font-size: 0.78rem;
    line-height: 1.2;
}

.nav-link {
    min-width: 0;
    display: inline-flex;
    align-items: center;
    gap: 10px;
    padding: 10px 12px;
    border-radius: 6px;
    border: 1px solid var(--color-border);
    background-color: transparent;
    color: var(--color-muted-foreground);
    text-decoration: none;
    transition:
        background-color 0.2s ease,
        color 0.2s ease,
        border-color 0.2s ease;
}

.nav-link:hover {
    color: var(--color-foreground);
    background-color: var(--color-secondary);
    border-color: var(--color-border);
}

.nav-link-active {
    color: var(--color-foreground);
    background-color: color-mix(
        in srgb,
        var(--color-primary) 10%,
        var(--color-card) 90%
    );
    border-color: color-mix(
        in srgb,
        var(--color-primary) 30%,
        var(--color-border) 70%
    );
}

.nav-icon {
    width: 17px;
    height: 17px;
    flex-shrink: 0;
}

.nav-copy {
    display: flex;
    flex-direction: column;
    gap: 2px;
}

.nav-label {
    font-size: 0.92rem;
    font-weight: 700;
    line-height: 1;
}

.nav-description {
    font-size: 0.72rem;
    line-height: 1.1;
    color: inherit;
    opacity: 0.75;
}

@media screen and (width < 720px) {
    .main {
        padding-top: 0;
    }

    .topbar {
        padding: 12px;
        border-radius: 0;
        flex-direction: column;
        align-items: stretch;
    }

    .navbar {
        width: 100%;
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
    }

    .nav-link {
        width: 100%;
    }
}

@media screen and (width < 520px) {
    .page-subtitle,
    .nav-description {
        display: none;
    }

    .nav-link {
        justify-content: center;
    }
}

@keyframes marquee {
    from {
        transform: translateX(0);
    }
    to {
        transform: translateX(-100%);
    }
}
</style>
